### ISSUE TITLE
Add contact

### ISSUE THREAD

**Issue by ChrisRenno** [ChrisRenno/cpreynolds.co.uk#4]

**Comment by akash-vartak** [comment]
I'm opening a pull request. Look into it.

**Comment by akash-vartak** [comment]
If you don't want pull requests and are currently learning then please close all the issues. They clutter the GitHub search. As you said in #6

**Comment by ChrisRenno** [comment]
No.
There's 8million other issues open.  I'm sure my 4 don't clutter the search up too much.
